### ISSUE TITLE
[ documentation, help wanted ] Disclaimer section about React apps needs clarification.

### ISSUE THREAD

**Issue by tashachin** [prifina/prifina-app-starter#10]
@tashachin why don't you do a deep dive and surface "all issues", then we can together review and start prioritizing actioning them.

_Originally posted by @mmlampinen in https://github.com/prifina/prifina-app-starter/issues/5#issuecomment-783521496_

Why are React apps incompatible with Prifina? Will require more research.

**Comment by tashachin** [comment]
@mmlampinen - Do you happen to know who added the "Warning"-style disclaimer about React? I'd like to clarify with them what's going on at the technical level.

**Comment by mmlampinen** [comment]
@tashachin Sure thing. Prifina's app is a "container app", which functions as a "container" for the apps built "on top", those "apps" then get embedded into the "container". 

From a technical point of view, Prifina's app is a "react app", and the apps built "on Prifina" are "dynamically rendered, remote react components". 

If the dev would build a "React app" for example through the normal process, it would not work. Does that make sense?

**Comment by tashachin** [comment]
@mmlampinen Several questions to drill down on: 

1. The first thing I think of when I see the word **container** is Docker technology, so I'm wondering if "container" is the most apt description to use. Is it a general metaphor, or tech jargon the way it is for Docker?
2. Is the starter-app repo a template/boilerplate for third-party developers to then _extend?_
3. Paraphrasing to see if I understand: The reason building a React app would not work is because Prifina is already its own React app (and in a sense, its own ecosystem), correct?

**Comment by mmlampinen** [comment]
1. Effectively here, container describes "an app within an app". It seems to be the term used.
2. They would download it locally, use the libraries, assets, components contained in it, to build their own app. So, yes.
3. Correct. (for longer explanation, it already has all the back end configurations and environment, that the "components" then utilize)

cc @tashachin
