### ISSUE TITLE
Proposed header/section: Prerequisites

### ISSUE THREAD

**Issue by tashachin** [prifina/prifina-app-starter#16]
It would be helpful to first-time contributors to have an overview of what technologies are involved (and to define said jargon right on the README).

i.e.
- React is a JavaScript framework for [ ??? ]
- BlendUI is our proprietary [ ??? ]
- React's component system [ ??? ]

*The [ ??? ] are to indicate anything I've forgotten off the top of my head; it does not mean those answers aren't already documented somewhere in our internal docs or Slack.

**Comment by DXPro25** [comment]
React is a JavaScript library that's intended for building interactive user interfaces.
BlendUI is the proprietary collection of reusable building block components used to build other components.
React's component system is designed to interface with other libraries and frameworks. It can be utilized as a simple component, state based component or even just a simple application.

**Comment by tashachin** [comment]
@DXPro25 - Hello! Would you like to be assigned to this issue?

**Comment by DXPro25** [comment]
Yes. Please and thank you.

**Comment by tashachin** [comment]
Let me know if you have questions, @DXPro25! Our general workflow is still a WIP and we welcome suggestions on how to improve it. For now, these are the steps:

- [ ] Fork this repo.
- [ ] Make changes on your own local branch.
- [ ] Create a pull request with your proposed changes.
- [ ] Await review.

Is that a good starting point?

**Comment by tashachin** [comment]
@DXPro25 Hello! It's been a while since we heard from you; are you still interested in working on this, or would you like to be removed?

**Comment by DXPro25** [comment]
Remove me please. Thank you.
