### ISSUE TITLE
Create "Quickstart" section in README.md

### ISSUE THREAD

**Issue by tashachin** [prifina/prifina-app-starter#27]
# Quickstart
Want to contribute to our docs? This tutorial will guide you through:

1. Forking this repo.
2. Installing the app locally.
3. Building the app.
4. Hosting the app.

## Forking this repo
First, create your own copy of this repository to work on by forking it on GitHub:

<img width="1255" alt="Screen Shot 2021-05-01 at 5 35 44 PM" src="https://user-images.githubusercontent.com/27714199/116798396-cf586500-aaa3-11eb-96eb-7a39bcc17b59.png">

## Installing the repo via zip download

<img width="920" alt="Screen Shot 2021-05-01 at 5 30 20 PM" src="https://user-images.githubusercontent.com/27714199/116798324-23af1500-aaa3-11eb-9b65-0da7007cc28a.png">

## Building the `app-starter`

Navigate into `prifina-app-starter-main` on your CLI.

Check that you have yarn installed with `yarn -v`. 

The console should return a version number in the standard format of `x.xx.xx` (i.e. `1.22.10`).

<img width="138" alt="Screen Shot 2021-05-01 at 6 15 52 PM" src="https://user-images.githubusercontent.com/27714199/116798930-480df000-aaa9-11eb-9656-9ed1cb96f070.png">

Run `yarn install`.

**WARNING:** Running `yarn install` outside of the repo will result in the following message and generate a new lockfile in your current directory.

<img width="269" alt="Screen Shot 2021-05-01 at 6 17 39 PM" src="https://user-images.githubusercontent.com/27714199/116798969-a9ce5a00-aaa9-11eb-89e8-cd59d6f80a1a.png">

Run `yarn start`. On successful compilation, it should look something like this:

<img width="907" alt="Screen Shot 2021-05-01 at 6 25 21 PM" src="https://user-images.githubusercontent.com/27714199/116799066-a5567100-aaaa-11eb-89ea-bd83151e5dd2.png">

## Hosting the app locally

On your browser (Chrome, Firefox, etc.), navigate to `localhost:8080`. You should see something like this if successful:

<img width="1249" alt="Screen Shot 2021-05-01 at 5 40 17 PM" src="https://user-images.githubusercontent.com/27714199/116798465-645b5e00-aaa4-11eb-85b1-d53889acf393.png">

**Comment by tashachin** [comment]
@mmlampinen Could you review this tutorial and let me know if it should be on the `README.md` or if you think I should create a `quickstart.md` and link it on the `README.md`?

**Comment by mmlampinen** [comment]
Hey @tashachin - I love it. The screenshots were a good point, we need to get things as practical as this. 

Let's go for simplest organization. I'd suggest the quistart.md and linking it at the top from the readme. We can then also link to it from the docs.prifina.com site.

**Comment by DavidPicarazzi** [comment]
Howdy test

**Comment by DavidPicarazzi** [comment]
Testing test

**Comment by DavidPicarazzi** [comment]
test

**Comment by DavidPicarazzi** [comment]
Test

**Comment by DavidPicarazzi** [comment]
> Test

testy

**Comment by DavidPicarazzi** [comment]
> Hey @tashachin - I love it. The screenshots were a good point, we need to get things as practical as this.
> 
> Let's go for simplest organization. I'd suggest the quistart.md and linking it at the top from the readme. We can then also link to it from the docs.prifina.com site.

test
