### ISSUE TITLE
Clean up and organize quickstart documentation

### ISSUE THREAD

**Issue by mmlampinen** [prifina/prifina-app-starter#5]
On both app-starter repo, file organization and publicly corresponding docs at docs.prifina.com

**Comment by tashachin** [comment]
I'd like to work on this!

**Comment by mmlampinen** [comment]
Go for it @tashachin - happy to collaborate here!

**Comment by tashachin** [comment]
@mmlampinen - You mentioned on Slack that we want to produce "working copy". Could you clarify what you meant by that?

**Comment by mmlampinen** [comment]
This is now a live developer product, and it works (you can actually build and run an app locally and in the browser), so let's target to get instructions that are helpful in using it.

**Comment by mmlampinen** [comment]
@tashachin why don't you do a deep dive and surface "all issues", then we can together review and start prioritizing actioning them.
